name: "Git credentials setup"
description: "Set up git credentials"

runs:
  using: "composite"
  steps:
    - name: Set up git credentials
      shell: bash
      run: |
        git config --global user.name 'vibe-gh'
        git config --global user.email 'vibe@monday.com'
