# This workflow will ensure that PR is titled according to semantic commits convention, so we can later create releases

name: Check PR semantic title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  check-pr-semantic-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.VIBE_GITHUB_TOKEN }}
        with:
          requireScope: false
