name: Chromatic

on: push

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-and-upload.yml
    secrets:
      npm_token: ${{ secrets.npm_token }}

  publish-chromatic:
    name: Publish Chromatic
    needs: build
    if: ${{ needs.build.outputs.has_changes == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.VIBE_GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Run Setup
        uses: ./.github/actions/setup
        with:
          npm_token: ${{ secrets.npm_token }}
      - uses: ./.github/actions/download-builds
      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          token: ${{ secrets.VIBE_GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/core
          exitOnceUploaded: true
